import { FormEvent, useEffect, useState } from "react";

type Lead = { id: string; name?: string; phone: string; created_at: string; status: string; photo_name?: string; telegram_status?: string };
export function AdminPage() {
  const [leads, setLeads] = useState<Lead[] | null>(null); const [error, setError] = useState("");
  const load = async () => { const r = await fetch("/api/admin/leads", { credentials: "same-origin" }); if (r.ok) setLeads(await r.json()); else setLeads(null); };
  useEffect(() => { let active = true; fetch("/api/admin/leads", { credentials: "same-origin" }).then(async r => { if (active) setLeads(r.ok ? await r.json() : null); }); return () => { active = false; }; }, []);
  const login = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: f.get("username"), password: f.get("password") }) }); if (!r.ok) setError("Неверные данные или вход временно ограничен"); else { setError(""); await load(); } };
  const action = async (id: string, kind: "close" | "delete") => { await fetch(`/api/admin/leads/${encodeURIComponent(id)}/${kind}`, { method: "POST" }); await load(); };
  if (!leads) return <main className="admin-page"><section className="admin-card"><h1>Панель заявок</h1><form className="admin-form" onSubmit={login}><input name="username" autoComplete="username" placeholder="Логин" required/><input name="password" type="password" autoComplete="current-password" placeholder="Пароль" required/><button className="button">Войти</button>{error && <p className="form-status">{error}</p>}</form></section></main>;
  return <main className="admin-page"><section className="admin-card"><h1>Заявки</h1><p>Доступ только после авторизации. Содержимое заявок не попадает в журнал доступа.</p><div className="admin-list">{leads.length === 0 && <p>Заявок нет.</p>}{leads.map(l => <article className="admin-lead" key={l.id}><strong>{l.name || "Имя не указано"}</strong><p><a href={`tel:${l.phone}`}>{l.phone}</a> · {new Date(l.created_at).toLocaleString("ru-RU")} · {l.status}{l.telegram_status ? ` · Telegram: ${l.telegram_status}` : ""}</p><div className="admin-actions">{l.photo_name && <a href={`/api/admin/leads/${l.id}/photo`} target="_blank">Открыть фото</a>}<button onClick={() => action(l.id, "close")}>Закрыть и запланировать удаление</button><button onClick={() => action(l.id, "delete")}>Удалить сейчас</button></div></article>)}</div></section></main>;
}
