export const siteConfig = {
  siteUrl: import.meta.env.VITE_SITE_URL || "",
  collectionEnabled: import.meta.env.VITE_DATA_COLLECTION_ENABLED === "true",
  metricaId: import.meta.env.VITE_METRICA_ID || "",
  documentVersion: import.meta.env.VITE_DOCUMENT_VERSION || "DRAFT-1",
  documentDate: import.meta.env.VITE_DOCUMENT_DATE || "Не утверждено",
  hosterLegalName: import.meta.env.VITE_HOSTER_LEGAL_NAME || "Не определён",
  hosterAddress: import.meta.env.VITE_HOSTER_ADDRESS || "Не определён",
  databaseLocation: import.meta.env.VITE_DATABASE_LOCATION || "Не подтверждено",
  operator: "ИП Струков Павел Александрович",
  inn: "504813988660",
  ogrnip: "326508100587469",
  address: "Московская область, г. Чехов, ул. Чехова, д. 37а, кв. 1",
  phone: "+7 (926) 725-48-58",
  phoneHref: "+79267254858",
  email: "myagkie-okna-mo@mail.ru",
  consentVersion: import.meta.env.VITE_CONSENT_VERSION || "DRAFT-1",
  analyticsConsentVersion: import.meta.env.VITE_ANALYTICS_CONSENT_VERSION || "DRAFT-1",
};
